#!/bin/bash
# 🚀 COMANDOS PARA DEPLOYMENT VÍA SSH EN EL SERVIDOR
# Copia y pega estos comandos en tu terminal SSH

echo "═══════════════════════════════════════════════════════════"
echo "  🚀 DEPLOYMENT INMOVA APP - VÍA SSH"
echo "═══════════════════════════════════════════════════════════"
echo ""

# PASO 1: Conectar al servidor
echo "📝 PASO 1: Conectar al servidor"
echo "────────────────────────────────────────────────────────────"
echo "Ejecuta en TU TERMINAL LOCAL:"
echo ""
echo "  ssh usuario@IP_SERVIDOR"
echo ""
echo "Ejemplo:"
echo "  ssh root@157.180.119.236"
echo "  O: ssh deploy@inmovaapp.com"
echo ""
read -p "Presiona ENTER cuando estés conectado al servidor..."

# PASO 2: Navegar al directorio de la app
echo ""
echo "📝 PASO 2: Navegar al directorio de la app"
echo "────────────────────────────────────────────────────────────"
echo "Ejecuta en EL SERVIDOR:"
echo ""
echo "  cd /opt/inmova-app"
echo "  # O donde esté tu app:"
echo "  # cd /home/deploy/inmova-app"
echo ""
read -p "Presiona ENTER cuando estés en el directorio..."

# PASO 3: Verificar estado actual
echo ""
echo "📝 PASO 3: Verificar estado actual"
echo "────────────────────────────────────────────────────────────"
echo "  git status"
echo "  git log --oneline -3"
echo ""

# PASO 4: Pull de cambios
echo ""
echo "📝 PASO 4: Pull de cambios desde GitHub"
echo "────────────────────────────────────────────────────────────"
echo "  git fetch origin"
echo "  git checkout main"
echo "  git merge origin/cursor/frontend-audit-inmovaapp-com-6336"
echo ""
echo "  # O si prefieres directamente:"
echo "  git pull origin cursor/frontend-audit-inmovaapp-com-6336"
echo ""

# PASO 5: Verificar qué deployment usas
echo ""
echo "📝 PASO 5: Deployment según tu configuración"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "¿Qué sistema usas en el servidor?"
echo ""
echo "A) DOCKER (docker-compose)"
echo "   docker-compose down"
echo "   docker-compose up -d --build"
echo "   docker-compose logs -f app"
echo ""
echo "B) PM2 (Node.js directo)"
echo "   npm install"
echo "   npm run build"
echo "   pm2 reload inmova-app"
echo "   pm2 logs inmova-app"
echo ""
echo "C) SYSTEMD (Next.js como servicio)"
echo "   npm install"
echo "   npm run build"
echo "   systemctl restart inmova-app"
echo "   systemctl status inmova-app"
echo ""
echo "D) MANUAL (npm start)"
echo "   npm install"
echo "   npm run build"
echo "   # Matar proceso viejo:"
echo "   fuser -k 3000/tcp"
echo "   # Iniciar nuevo:"
echo "   npm start &"
echo ""

# PASO 6: Verificar
echo ""
echo "📝 PASO 6: Verificar deployment"
echo "────────────────────────────────────────────────────────────"
echo "  # Health check"
echo "  curl http://localhost:3000/api/health"
echo ""
echo "  # Ver logs"
echo "  # Docker: docker-compose logs -f app"
echo "  # PM2: pm2 logs inmova-app"
echo "  # Systemd: journalctl -u inmova-app -f"
echo ""
echo "  # Test desde fuera del servidor (desde TU MÁQUINA)"
echo "  curl https://inmovaapp.com/api/health"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  ✅ DEPLOYMENT COMPLETADO"
echo "═══════════════════════════════════════════════════════════"
