# Dockerfile for INMOVA Next.js Application
# Railway Deployment - Optimized for Standalone Mode

# ==========================================
# STAGE 1: Base Dependencies
# ==========================================
FROM node:18-alpine AS base

RUN apk add --no-cache \
    libc6-compat \
    openssl \
    ca-certificates

WORKDIR /app

# ==========================================
# STAGE 2: Build Application
# ==========================================
FROM base AS builder

WORKDIR /app

# Copy package files
COPY package.json yarn.lock* ./

# Copy Prisma schema BEFORE yarn install (for postinstall hook)
COPY prisma ./prisma

# Install ALL dependencies (including devDependencies for build)
RUN yarn install --frozen-lockfile --network-timeout 100000

# Copy application source
COPY . .

# Build the application
# - prisma generate: Ensures Prisma Client is available
# - next build: Compiles with standalone output mode
RUN NODE_OPTIONS="--max-old-space-size=4096" yarn build

# ==========================================
# STAGE 3: Production Runner (Standalone)
# ==========================================
FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy standalone build
# When output: 'standalone' is set in next.config.js,
# Next.js generates .next/standalone/ with everything needed
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Copy Prisma schema for runtime (needed by some Prisma operations)
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma

# Copy Prisma Client (in case it's needed separately)
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/@prisma ./node_modules/@prisma

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the standalone server
# .next/standalone/server.js is generated by Next.js standalone mode
CMD ["node", "server.js"]
