import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import {
  addMonths,
  subDays,
  startOfMonth,
  setDate,
  setHours,
  setMinutes,
} from 'date-fns';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const COLORS = {
  contrato: '#3B82F6',
  seguro: '#22C55E',
  pago: '#F59E0B',
  mantenimiento: '#EF4444',
  ipc: '#8B5CF6',
};

interface AutoCalendarEvent {
  id: string;
  titulo: string;
  descripcion?: string;
  tipo: string;
  prioridad: string;
  fechaInicio: string;
  fechaFin?: string;
  todoElDia: boolean;
  color?: string;
  autoGenerated: boolean;
  sourceEntity?: string;
  sourceId?: string;
  completado: boolean;
  cancelado: boolean;
}

function generateMockEvents(): AutoCalendarEvent[] {
  const now = new Date();
  const events: AutoCalendarEvent[] = [];
  let idCounter = 1;

  const genId = () => `auto-${idCounter++}`;

  // Contract mock data - 2 contracts
  const contract1Start = setDate(setHours(setMinutes(now, 0), 0), 15);
  const contract1End = addMonths(contract1Start, 12);
  const contract2Start = addMonths(setDate(setHours(setMinutes(now, 0), 0), 1), -3);
  const contract2End = addMonths(contract2Start, 12);

  // Contract 1 events
  events.push({
    id: genId(),
    titulo: 'Inicio de contrato - Calle Mayor 12',
    descripcion: 'Inicio del contrato de arrendamiento',
    tipo: 'contrato',
    prioridad: 'media',
    fechaInicio: contract1Start.toISOString(),
    fechaFin: contract1Start.toISOString(),
    todoElDia: true,
    color: COLORS.contrato,
    autoGenerated: true,
    sourceEntity: 'contract',
    sourceId: 'contract-1',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Vencimiento contrato - Calle Mayor 12',
    descripcion: 'Fecha fin del contrato de arrendamiento',
    tipo: 'contrato',
    prioridad: 'alta',
    fechaInicio: contract1End.toISOString(),
    fechaFin: contract1End.toISOString(),
    todoElDia: true,
    color: COLORS.contrato,
    autoGenerated: true,
    sourceEntity: 'contract',
    sourceId: 'contract-1',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Revisión IPC anual - Calle Mayor 12',
    descripcion: 'Revisión anual del IPC según cláusula contractual',
    tipo: 'ipc',
    prioridad: 'media',
    fechaInicio: addMonths(contract1Start, 12).toISOString(),
    fechaFin: addMonths(contract1Start, 12).toISOString(),
    todoElDia: true,
    color: COLORS.ipc,
    autoGenerated: true,
    sourceEntity: 'contract',
    sourceId: 'contract-1',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Renovación contrato - Calle Mayor 12',
    descripcion: 'Recordatorio: contrato vence en 30 días',
    tipo: 'contrato',
    prioridad: 'alta',
    fechaInicio: subDays(contract1End, 30).toISOString(),
    fechaFin: subDays(contract1End, 30).toISOString(),
    todoElDia: true,
    color: COLORS.contrato,
    autoGenerated: true,
    sourceEntity: 'contract',
    sourceId: 'contract-1',
    completado: false,
    cancelado: false,
  });

  // Contract 2 events
  events.push({
    id: genId(),
    titulo: 'Inicio de contrato - Av. Diagonal 45',
    descripcion: 'Inicio del contrato de arrendamiento',
    tipo: 'contrato',
    prioridad: 'media',
    fechaInicio: contract2Start.toISOString(),
    fechaFin: contract2Start.toISOString(),
    todoElDia: true,
    color: COLORS.contrato,
    autoGenerated: true,
    sourceEntity: 'contract',
    sourceId: 'contract-2',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Vencimiento contrato - Av. Diagonal 45',
    descripcion: 'Fecha fin del contrato de arrendamiento',
    tipo: 'contrato',
    prioridad: 'alta',
    fechaInicio: contract2End.toISOString(),
    fechaFin: contract2End.toISOString(),
    todoElDia: true,
    color: COLORS.contrato,
    autoGenerated: true,
    sourceEntity: 'contract',
    sourceId: 'contract-2',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Renovación contrato - Av. Diagonal 45',
    descripcion: 'Recordatorio: contrato vence en 30 días',
    tipo: 'contrato',
    prioridad: 'alta',
    fechaInicio: subDays(contract2End, 30).toISOString(),
    fechaFin: subDays(contract2End, 30).toISOString(),
    todoElDia: true,
    color: COLORS.contrato,
    autoGenerated: true,
    sourceEntity: 'contract',
    sourceId: 'contract-2',
    completado: false,
    cancelado: false,
  });

  // Insurance mock data - 2 policies
  const insurance1Expiry = addMonths(now, 4);
  const insurance2Expiry = addMonths(now, 8);

  events.push({
    id: genId(),
    titulo: 'Vencimiento póliza - Hogar Comunidad',
    descripcion: 'Póliza de hogar vence. Renovar antes de la fecha.',
    tipo: 'seguro',
    prioridad: 'alta',
    fechaInicio: insurance1Expiry.toISOString(),
    fechaFin: insurance1Expiry.toISOString(),
    todoElDia: true,
    color: COLORS.seguro,
    autoGenerated: true,
    sourceEntity: 'insurance',
    sourceId: 'insurance-1',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Renovación póliza - Hogar Comunidad',
    descripcion: 'Recordatorio: póliza vence en 60 días',
    tipo: 'seguro',
    prioridad: 'media',
    fechaInicio: subDays(insurance1Expiry, 60).toISOString(),
    fechaFin: subDays(insurance1Expiry, 60).toISOString(),
    todoElDia: true,
    color: COLORS.seguro,
    autoGenerated: true,
    sourceEntity: 'insurance',
    sourceId: 'insurance-1',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Vencimiento póliza - Comunidad Edificio B',
    descripcion: 'Póliza de comunidad vence.',
    tipo: 'seguro',
    prioridad: 'alta',
    fechaInicio: insurance2Expiry.toISOString(),
    fechaFin: insurance2Expiry.toISOString(),
    todoElDia: true,
    color: COLORS.seguro,
    autoGenerated: true,
    sourceEntity: 'insurance',
    sourceId: 'insurance-2',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'Renovación póliza - Comunidad Edificio B',
    descripcion: 'Recordatorio: póliza vence en 60 días',
    tipo: 'seguro',
    prioridad: 'media',
    fechaInicio: subDays(insurance2Expiry, 60).toISOString(),
    fechaFin: subDays(insurance2Expiry, 60).toISOString(),
    todoElDia: true,
    color: COLORS.seguro,
    autoGenerated: true,
    sourceEntity: 'insurance',
    sourceId: 'insurance-2',
    completado: false,
    cancelado: false,
  });

  // Payment events - cobro mensual (1st of each month) for next 6 months
  for (let i = 0; i < 6; i++) {
    const payDate = setDate(startOfMonth(addMonths(now, i)), 1);
    events.push({
      id: genId(),
      titulo: 'Cobro mensual renta - Calle Mayor 12',
      descripcion: 'Vencimiento cobro de renta mensual',
      tipo: 'pago',
      prioridad: 'alta',
      fechaInicio: payDate.toISOString(),
      fechaFin: payDate.toISOString(),
      todoElDia: true,
      color: COLORS.pago,
      autoGenerated: true,
      sourceEntity: 'payment',
      sourceId: `payment-${i}`,
      completado: false,
      cancelado: false,
    });
  }

  // Maintenance events
  const calderaDate = addMonths(now, 2);
  const itvDate = addMonths(now, 5);

  events.push({
    id: genId(),
    titulo: 'Revisión caldera anual - Edificio Central',
    descripcion: 'Revisión obligatoria de caldera según normativa',
    tipo: 'mantenimiento',
    prioridad: 'alta',
    fechaInicio: calderaDate.toISOString(),
    fechaFin: calderaDate.toISOString(),
    todoElDia: true,
    color: COLORS.mantenimiento,
    autoGenerated: true,
    sourceEntity: 'maintenance',
    sourceId: 'maintenance-1',
    completado: false,
    cancelado: false,
  });

  events.push({
    id: genId(),
    titulo: 'ITV ascensor - Edificio Central',
    descripcion: 'Inspección técnica de ascensor',
    tipo: 'mantenimiento',
    prioridad: 'critica',
    fechaInicio: itvDate.toISOString(),
    fechaFin: itvDate.toISOString(),
    todoElDia: true,
    color: COLORS.mantenimiento,
    autoGenerated: true,
    sourceEntity: 'maintenance',
    sourceId: 'maintenance-2',
    completado: false,
    cancelado: false,
  });

  // Filter to next 12 months only
  const twelveMonthsLater = addMonths(now, 12);
  return events.filter((e) => new Date(e.fechaInicio) <= twelveMonthsLater);
}

/**
 * GET /api/calendar/auto-events
 * Returns auto-generated events from contracts and insurances
 */
export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.companyId) {
      return NextResponse.json({ error: 'No autenticado' }, { status: 401 });
    }

    const events = generateMockEvents();
    return NextResponse.json(events);
  } catch (error) {
    console.error('[Auto Events] Error:', error);
    return NextResponse.json(
      { error: 'Error generando eventos automáticos' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/calendar/auto-events
 * Triggers auto-generation for a specific entity
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.companyId) {
      return NextResponse.json({ error: 'No autenticado' }, { status: 401 });
    }

    const body = await request.json();
    const { tipo, entidadOrigen, entidadId } = body;

    // For now just return success - future: generate events for specific entity
    return NextResponse.json({
      success: true,
      message: 'Generación de eventos solicitada',
      tipo,
      entidadOrigen,
      entidadId,
    });
  } catch (error) {
    console.error('[Auto Events POST] Error:', error);
    return NextResponse.json(
      { error: 'Error procesando solicitud' },
      { status: 500 }
    );
  }
}
