/**
 * Constantes y configuraciones del Sidebar
 */

// Mapeo de rutas a códigos de módulos
export const ROUTE_TO_MODULE: Record<string, string> = {
  '/': 'dashboard',
  '/dashboard': 'dashboard',
  '/dashboard': 'dashboard',
  '/edificios': 'edificios',
  '/unidades': 'unidades',
  '/garajes-trasteros': 'unidades',
  '/inquilinos': 'inquilinos',
  '/contratos': 'contratos',
  '/pagos': 'pagos',
  '/pagos/sepa': 'pagos',
  '/finanzas/conciliacion': 'pagos',
  '/mantenimiento': 'mantenimiento',
  '/calendario': 'calendario',
  '/chat': 'chat',
  '/bi': 'bi',
  '/reportes': 'reportes',
  '/documentos': 'documentos',
  '/room-rental': 'room_rental',
  '/proveedores': 'proveedores',
  '/gastos': 'gastos',
  '/tareas': 'tareas',
  '/candidatos': 'candidatos',
  '/crm': 'crm',
  '/notificaciones': 'notificaciones',
  '/incidencias': 'incidencias',
  '/ocr': 'ocr',
  '/redes-sociales': 'redes_sociales',
  '/admin/dashboard': 'admin_dashboard',
  '/admin/clientes': 'gestion_clientes',
  '/admin/planes': 'admin_planes',
  '/admin/ewoorker-planes': 'admin_ewoorker_planes',
  '/admin/facturacion-b2b': 'admin_facturacion_b2b',
  '/admin/personalizacion': 'admin_personalizacion',
  '/admin/activity': 'admin_activity',
  '/admin/alertas': 'admin_alertas',
  '/admin/portales-externos': 'admin_portales_externos',
  '/admin/aprobaciones': 'admin_aprobaciones',
  '/admin/reportes-programados': 'admin_reportes_programados',
  '/admin/importar': 'admin_importar',
  '/admin/ocr-import': 'admin_ocr_import',
  '/api-docs': 'api_docs',
  '/admin/configuracion': 'configuracion',
  '/admin/usuarios': 'usuarios',
  '/admin/modulos': 'configuracion',
  '/admin/sales-team': 'admin_sales_team',
  '/analytics': 'analytics',
  '/str/listings': 'str_listings',
  '/str-housekeeping': 'str_housekeeping',
  '/str/bookings': 'str_bookings',
  '/str/channels': 'str_channels',
  '/str-advanced': 'str_advanced',
  '/str-advanced/channel-manager': 'str_advanced',
  '/str-advanced/revenue': 'str_advanced',
  '/str-advanced/housekeeping': 'str_advanced',
  '/str-advanced/guest-experience': 'str_advanced',
  '/str-advanced/legal': 'str_advanced',
  '/flipping/projects': 'flipping_projects',
  '/construction/projects': 'construction_projects',
  '/professional/projects': 'professional_projects',
  '/anuncios': 'anuncios',
  '/votaciones': 'votaciones',
  '/reuniones': 'reuniones',
  '/reservas': 'reservas',
  '/admin-fincas': 'admin_fincas',
  '/admin-fincas/comunidades': 'admin_fincas',
  '/admin-fincas/facturas': 'admin_fincas',
  '/admin-fincas/libro-caja': 'admin_fincas',
  '/admin-fincas/informes': 'admin_fincas',
  '/valoraciones': 'valoraciones',
  '/publicaciones': 'publicaciones',
  '/screening': 'screening',
  '/galerias': 'galerias',
  '/certificaciones': 'certificaciones',
  '/seguros': 'seguros',
  '/inspecciones': 'inspecciones',
  '/visitas': 'visitas',
  '/ordenes-trabajo': 'ordenes_trabajo',
  '/firma-digital': 'firma_digital',
  '/legal': 'legal',
  '/open-banking': 'open_banking',
  '/marketplace': 'marketplace',
  '/sms': 'sms',
  '/dashboard/community': 'community_management',
  '/esg': 'esg',
  '/iot': 'iot',
  '/blockchain': 'blockchain',
  '/tours-virtuales': 'tours_virtuales',
  '/economia-circular': 'economia_circular',
  '/auditoria': 'auditoria',
  '/seguridad-compliance': 'seguridad_compliance',

  // === Catalog routes (synced from MODULOS_CATALOGO) ===
  '/admin/cupones': 'admin_cupones',
  '/admin/notificaciones-masivas': 'admin_notificaciones',
  '/admin/onboarding': 'admin_onboarding',
  '/admin/system-logs': 'admin_logs',
  '/asistente-ia': 'ai_assistant',
  '/automatizacion': 'automatizacion',
  '/coliving/propiedades': 'coliving',
  '/comercial': 'alquiler_comercial',
  '/comunidad-social': 'comunidad_social',
  '/comunidades': 'admin_fincas',
  '/construccion': 'construccion_dashboard',
  '/construccion/proyectos': 'construccion_projects',
  '/contabilidad': 'contabilidad',
  '/dashboard/herramientas': 'herramientas_inversion',
  '/dashboard/servicios': 'servicios',
  '/edificios-inteligentes': 'iot',
  '/energia': 'energia',
  '/estadisticas': 'estadisticas',
  '/ewoorker': 'ewoorker',
  '/facturacion': 'facturacion',
  '/finanzas': 'finanzas',
  '/garantias': 'garantias',
  '/hospitality': 'hospitality',
  '/informes': 'informes',
  '/instalaciones-deportivas': 'instalaciones_deportivas',
  '/inversiones': 'holding_grupo',
  '/knowledge-base': 'knowledge_base',
  '/licitaciones': 'licitaciones',
  '/mantenimiento-pro': 'mantenimiento_pro',
  '/matching': 'matching',
  '/media-estancia': 'media_estancia',
  '/plantillas': 'plantillas',
  '/portal-comercial': 'portal_comercial',
  '/portal-inquilino': 'portal_inquilino',
  '/portal-proveedor': 'portal_proveedor',
  '/presupuestos': 'presupuestos',
  '/promociones': 'promociones',
  '/propiedades': 'gestion_inmobiliaria',
  '/puntos-carga': 'puntos_carga',
  '/real-estate-developer': 'real_estate_developer',
  '/recordatorios': 'recordatorios',
  '/red-agentes': 'red_agentes',
  '/reviews': 'reviews',
  '/servicios-limpieza': 'servicios_limpieza',
  '/sincronizacion': 'sincronizacion',
  '/sincronizacion-avanzada': 'sincronizacion_avanzada',
  '/soporte': 'soporte',
  '/str': 'str',
  '/str/reviews': 'str_reviews',
  '/student-housing': 'student_housing',
  '/sugerencias': 'sugerencias',
  '/traditional-rental': 'alquiler_residencial',
  '/valoracion-ia': 'valoracion_ia',
  '/viajes-corporativos': 'viajes_corporativos',
  '/vivienda-social': 'vivienda_social',
  '/warehouse': 'warehouse',
  '/workflows': 'workflows',
  '/workspace': 'workspace',

  // === New module mappings (pages without catalog entry) ===
  '/admin': 'admin',
  '/alertas': 'alertas',
  '/automatizacion-resumen': 'automatizacion',
  '/ayuda': 'ayuda',
  '/community': 'community',
  '/comunicaciones': 'comunicaciones',
  '/comunidad': 'comunidad',
  '/configuracion': 'configuracion',
  '/construction': 'construccion_dashboard',
  '/cupones': 'admin_cupones',
  '/dashboard-adaptive': 'dashboard',
  '/developers': 'api_docs',
  '/energia-solar': 'energia',
  '/espacios-coworking': 'alquiler_comercial',
  '/ewoorker-landing': 'ewoorker',
  '/facturas': 'facturacion',
  '/fianzas': 'finanzas',
  '/flipping': 'flipping_projects',
  '/gestion-incidencias': 'incidencias',
  '/guardias': 'mantenimiento',
  '/huerto-urbano': 'economia_circular',
  '/huertos-urbanos': 'economia_circular',
  '/impuestos': 'finanzas',
  '/inspeccion-digital': 'inspecciones',
  '/integraciones': 'configuracion',
  '/inventario-mantenimiento': 'mantenimiento_pro',
  '/leads': 'crm',
  '/microtransacciones': 'pagos',
  '/morosidad': 'morosidad',
  '/obras': 'construccion_dashboard',
  '/partners': 'red_agentes',
  '/partners-program': 'red_agentes',
  '/perfil': 'configuracion',
  '/permisos': 'configuracion',
  '/planes': 'admin_planes',
  '/planificacion': 'calendario',
  '/plantillas-legales': 'plantillas',
  '/professional': 'professional_projects',
  '/proveedor': 'proveedores',
  '/proyectos-renovacion': 'construccion_dashboard',
  '/recomendaciones': 'sugerencias',
  '/renovaciones': 'renovaciones_contratos',
  '/renovaciones-contratos': 'renovaciones_contratos',
  '/reportes-programados': 'admin_reportes_programados',
  '/retail': 'alquiler_comercial',
  '/salas-reuniones': 'reservas',
  '/seguridad': 'seguridad_compliance',
  '/servicios-concierge': 'servicios',
  '/stock-gestion': 'warehouse',
  '/subastas': 'holding_grupo',
  '/suscripciones': 'admin_planes',
  '/turismo-alquiler': 'str',
  '/usuarios': 'usuarios',
  '/vacaciones': 'calendario',
  '/vencimientos': 'contratos',
  '/verificacion-inquilinos': 'screening',
  '/warranty-management': 'garantias',
};

// Módulos core que siempre deben mostrarse
export const CORE_MODULES = [
  'dashboard',
  'edificios',
  'unidades',
  'inquilinos',
  'contratos',
  'pagos',
  'mantenimiento',
  'calendario',
  'chat',
  'proveedores',
  'gastos',
  'tareas',
  'candidatos',
  'notificaciones',
  'incidencias',
  'ocr',
  'documentos',
  'reportes',
  'bi',
  'analytics',
  'crm',
  'anuncios',
  'votaciones',
  'reuniones',
  'reservas',
  'valoraciones',
  'publicaciones',
  'screening',
  'galerias',
  'certificaciones',
  'seguros',
  'inspecciones',
  'visitas',
  'ordenes_trabajo',
  'firma_digital',
  'legal',
  'open_banking',
  'marketplace',
  'sms',
  'room_rental',
  'community_management',
  'esg',
  'iot',
  'blockchain',
  'tours_virtuales',
  'economia_circular',
  'auditoria',
  'seguridad_compliance',
  'gestion_clientes',
  'admin_dashboard',
  'admin_planes',
  'admin_facturacion_b2b',
  'admin_personalizacion',
  'admin_activity',
  'admin_alertas',
  'admin_aprobaciones',
  'admin_reportes_programados',
  'admin_importar',
  'api_docs',
  'configuracion',
  'usuarios',
  'flipping_projects',
  'construction_projects',
  'professional_projects',
  'str_listings',
  'str_bookings',
  'str_channels',
  'str_advanced',
  'str_housekeeping',
  'admin_fincas',
  'admin_sales_team',
  'admin_portales_externos',
];

// Estado inicial de secciones expandidas
export const DEFAULT_EXPANDED_SECTIONS = {
  favorites: true,
  dashboard: true,
  alquilerResidencial: true,
  str: false,
  coLiving: false,
  buildToRent: false,
  flipping: false,
  comercial: false,
  adminFincas: false,
  finanzas: true,
  analytics: false,
  operaciones: true,
  comunicaciones: false,
  documentosLegal: false,
  crmMarketing: false,
  automatizacion: false,
  innovacion: false,
  soporte: false,
  operador: true,
  administradorEmpresa: true,
  superAdminPlatform: false,
};
