'use client';

import { useEffect, useState, useCallback } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { RefreshCw } from 'lucide-react';
import { toast } from 'sonner';

export interface CalendarEvent {
  id: string;
  titulo: string;
  descripcion?: string;
  tipo: string;
  prioridad: string;
  fechaInicio: string;
  fechaFin?: string;
  todoElDia: boolean;
  ubicacion?: string;
  color?: string;
  completado?: boolean;
  cancelado?: boolean;
  autoGenerated?: boolean;
  sourceEntity?: string;
  sourceId?: string;
}

interface AutoEventsBannerProps {
  onEventsLoaded: (events: CalendarEvent[]) => void;
  enabled: boolean;
  onToggle: (enabled: boolean) => void;
}

const COLOR_LEGEND = [
  { label: 'Contratos', color: '#3B82F6', emoji: '🔵' },
  { label: 'Seguros', color: '#22C55E', emoji: '🟢' },
  { label: 'Pagos', color: '#F59E0B', emoji: '🟡' },
  { label: 'Mantenimiento', color: '#EF4444', emoji: '🔴' },
  { label: 'IPC', color: '#8B5CF6', emoji: '🟣' },
];

export function AutoEventsBanner({
  onEventsLoaded,
  enabled,
  onToggle,
}: AutoEventsBannerProps) {
  const [eventCount, setEventCount] = useState(0);
  const [loading, setLoading] = useState(false);

  const fetchAutoEvents = useCallback(async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/calendar/auto-events');
      if (!response.ok) throw new Error('Error cargando eventos automáticos');

      const events: CalendarEvent[] = await response.json();

      // Normalize to match CalendarEvent interface
      const normalizedEvents: CalendarEvent[] = events.map((e) => ({
        ...e,
        completado: e.completado ?? false,
        cancelado: e.cancelado ?? false,
      }));

      setEventCount(normalizedEvents.length);
      onEventsLoaded(normalizedEvents);
    } catch (error) {
      console.error('Error fetching auto events:', error);
      toast.error('Error al cargar eventos automáticos');
      onEventsLoaded([]);
      setEventCount(0);
    } finally {
      setLoading(false);
    }
  }, [onEventsLoaded]);

  useEffect(() => {
    if (enabled) {
      fetchAutoEvents();
    } else {
      onEventsLoaded([]);
      setEventCount(0);
    }
  }, [enabled, fetchAutoEvents, onEventsLoaded]);

  return (
    <Card className="mb-6">
      <CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap items-center gap-4">
          <div className="flex items-center space-x-2">
            <Switch
              id="auto-events"
              checked={enabled}
              onCheckedChange={onToggle}
              disabled={loading}
            />
            <Label htmlFor="auto-events" className="cursor-pointer font-medium">
              Eventos automáticos
            </Label>
          </div>

          {enabled && (
            <>
              <span className="text-sm text-muted-foreground">
                {eventCount} eventos automáticos generados
              </span>

              <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                {COLOR_LEGEND.map((item) => (
                  <span
                    key={item.label}
                    className="flex items-center gap-1"
                    title={item.label}
                  >
                    <span
                      className="inline-block h-3 w-3 rounded-full"
                      style={{ backgroundColor: item.color }}
                    />
                    {item.label}
                  </span>
                ))}
              </div>
            </>
          )}
        </div>

        {enabled && (
          <Button
            variant="outline"
            size="sm"
            onClick={fetchAutoEvents}
            disabled={loading}
            className="gap-2 shrink-0"
          >
            <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
            Regenerar eventos
          </Button>
        )}
      </CardContent>
    </Card>
  );
}
