-- AlterTable
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "concepto" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "referencia" TEXT;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "baseImponible" DOUBLE PRECISION;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "iva" DOUBLE PRECISION;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "irpf" DOUBLE PRECISION;
